builds:
- main: ./cmd/ 
  id: "SNDP"
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
archives:
  - name_template: "SNDP_{{ .Version }}_{{ .OS }}_{{ .Arch }}"
    
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'