builds:
- main: ./cmd/
  id: LINUX_SNDP
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
- main: ./cmd/
  id: WINDOWS_SNDP
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
- main: ./cmd/
  id: DARWIN_SNDP
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64