services:

  mysql:
    image: mysql
    container_name: mysql
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "iot"
    # volumes:
    #   - db:/var/lib/mysql
    #   - ./seeds/init.sql:/data/application/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  keycloak:
    image:  quay.io/keycloak/keycloak:latest
    restart: always # keep the server running
    command: start-dev
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_PASSWORD=my-secret-pw
      - KC_DB_URL=jdbc:mysql://192.168.1.31:3306/keycloak
      - KC_DB_USERNAME=root

      - DB_VENDOR=mysql
      - DB_USER=root
      - DB_ADDR=mysql
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_PASSWORD=my-secret-pw
      # - KEYCLOAK_HOSTNAME=keycloak
volumes:
  db:
    name: db
