server.port: 0.0.0.0:9080

db.type: mysql
db.host: localhost
db.user: root
db.password: my-secret-pw
db.name: iot

oidc.issuer_url: "http://localhost:8080/auth/realms/SNDP"
oidc.client_id: sndp