basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /health/health:
    get:
      description: health check for service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Responds with 200 if service is running
  /health/ping:
    get:
      description: health check for service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Responds with 200 if service is running
swagger: "2.0"
