name: Build AAR with gomobile

on:
  push:
    paths:
      - 'cmd/gobind/**'  # Trigger only when files under cmd/gobind are changed

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      id: go

    - name: Install gomobile
      run: go install golang.org/x/mobile/cmd/gomobile@latest
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
        add-to-path: false
    - name: Build AAR
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        # Replace './cmd/stream' with the actual path to your Go package.
        gomobile bind -ldflags="-w -s" -target=android/arm -javapkg rogo.iot.module ./cmd/gobind

    - name: Archive AAR
      uses: actions/upload-artifact@v2
      with:
        name: iot-library
        path: rogo.iot.module.logger.aar
